### ISSUE TITLE
color issue

### ISSUE THREAD

**Issue by dailoi280702** [LunarVim/horizon.nvim#1]
I think some syntax highlighting is missing.
The yellow keywords in css and ts in this theme are the same as default.
![image](https://user-images.githubusercontent.com/87962065/181917306-c226e996-3bb4-4f13-835a-694486d22466.png)

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/181919518-a82b8bcd-d238-45bf-bed5-23253a1ee9d8.png)

My guess is that you're using an older version of neovim and this colorscheme is taking advantage of newer features. When it encounters that new features the colorscheme stops setting highlights.

do you see anything in:

`:messages`
or
`Notifications`?

**Comment by akinsho** [comment]
I think I'm seeing the same issue as the OP I'm on neovim nightly (from yesterday) though so unlikely to be too old, there are also no messages or notifications.

Not sure what the intended highlight group that should be in the screenshot should be but in my case highlights for `Todo`, `Error` etc. are highlighted using the default neovim colors which are just
 `Todo           xxx ctermfg=0 ctermbg=11 guifg=Blue guibg=Yellow `

Looking into the code base
https://github.com/LunarVim/horizon.nvim/blob/47605b017cbd39bcb7870e5116bae8e2c1bec3ed/horizon.template#L176-L182

They seem to be commented out so maybe this would account for the missing highlights @dailoi280702 sees as well

**Comment by dailoi280702** [comment]
I found that the problem came from my treesitter config. I forgot to add the 'css' parser. 
![image](https://user-images.githubusercontent.com/87962065/181923847-16e27d2b-a137-4be9-977a-99b5530cd075.png)
Thank you for making this great color scheme. Have a good day sir.
