### ISSUE TITLE
[Feature] Support the horizon light variant 

### ISSUE THREAD

**Issue by akinsho** [LunarVim/horizon.nvim#6]
Hi 👋🏿,

It would be great if the light variant of this theme could also be supported, for those times when you need to share your screen, or it's too bright for a dark theme.

I know this theme is generated using a rust crate, but it doesn't seem to incorporate light variants that can be toggled using the `vim.opt.background = 'light'` so maybe the functionality would need to be added to the generator tool first.

**Comment by akinsho** [comment]
I've implemented this over in https://github.com/akinsho/horizon.nvim.

**Comment by brainlessbitch** [comment]
> I've implemented this over in https://github.com/akinsho/horizon.nvim.

@akinsho, your implementation is broken T T

i get this if i try to use the light version
`Error detected while processing /home/exoess/.local/share/nvim/lazy/horizon.nvim/colors/horizon.lua:
E5113: Error while calling lua chunk: ...local/share/nvim/lazy/horizon.nvim/lua/horizon/theme.lua:7: cannot alter a color without specifying a
 color and percentage
stack traceback:
        [C]: in function 'assert'
        ...local/share/nvim/lazy/horizon.nvim/lua/horizon/theme.lua:7: in function 'tint'
        ...local/share/nvim/lazy/horizon.nvim/lua/horizon/theme.lua:35: in function 'get_custom_highlights'
        ...local/share/nvim/lazy/horizon.nvim/lua/horizon/theme.lua:613: in function 'set_highlights'
        ....local/share/nvim/lazy/horizon.nvim/lua/horizon/init.lua:41: in function 'setup'
        ...s/.local/share/nvim/lazy/horizon.nvim/colors/horizon.lua:1: in main chunk`
